### ISSUE TITLE
[NewUI] Auto backups suddenly result in 0 byte files

### ISSUE THREAD

**Issue by fennectech** [J-D-K/JKSV#113]
Accurate as of https://github.com/J-D-K/JKSV/commit/1001eeb8de51d2e1bb587b7012f2192a5761613f

**Comment by fennectech** [comment]
Its also possible to scroll off the screen on the dual pane file browser

**Comment by fennectech** [comment]
also  once you enter the dual pane browsers  the close action does nothing  you must exit the app

**Comment by J-D-K** [comment]
Minus closes the browser mode like the original for now. If you're using left or right to jump through the list it's possible to do that because I still need to update the logic from the old controls to scroll.

Now, by auto backup you mean holding L or R while selecting new? It's all fed through the same function so I don't really understand why that'd be happening now.

**Comment by fennectech** [comment]
I'm talking when restoring a save. The auto backup it makes now results in 0 byte files.

**Comment by J-D-K** [comment]
OK. I see what it is now. I added a thread manager so I could get around UI hangs for certain system calls and functions. They're always executed in the order pushed to the manager, so what happens here is:
* The auto-backup function reads off everything, creates what folders/zip it needs to, and queues up the file copying threads.
* Before the thread manager gets going, the main thread calls `fs::wipeSave`. This function is to clear out the previous data before restoring.
* Since the files don't exist anymore by the time the threads are run, they bail instead of crashing as they should, giving empty files.

Solution: Make `fs::wipeSave` a threaded function which won't be difficult.

**Comment by fennectech** [comment]
Glad i was of help :)
