### ISSUE TITLE
Compat with Yuzu?

### ISSUE THREAD

**Issue by lxly9** [J-D-K/JKSV#158]
Hi, would it be possible to use JKSV with yuzu as to load BCAT files for (in my case) ACNH, etc.? I have all the BCAT files needed already though the tutorial it comes with is switch/homebrew only. 
Ryujinx is not an option for me, as it isn't really working/isn't performing well

**Comment by J-D-K** [comment]
I'm not completely sure why JKSV doesn't work with emulators. I've never looked into either because it seems kind of pointless to me. Emulators just use a folder instead of a container and the saves are easily found and edited. JKSV would probably make it a bit easier, I don't if they emulate the save id system and incrementing it like the Switch does, but it's not a priority to get it working there. Maybe later if I get bored enough and have time, but for now, sorry, nope.
