### ISSUE TITLE
Compatible with Firmware 15.0.0?

### ISSUE THREAD

**Issue by waylonflinn** [J-D-K/JKSV#161]
Having trouble with a few save files created with JKSV on the new Firmware. Does JKSV require an update to be compatible?

**Comment by J-D-K** [comment]
I'm not actually sure. I haven't had time at a to keep up with everything. Maybe this weekend I'll be able to check. What games are having problems?

**Comment by waylonflinn** [comment]
Lots of games work fine but ‘Mario Kart 8 Deluxe’ and ‘Fire Emblem: Three
Houses’ both seem to be having issues for me out of the 12 or so games I’ve
tried.
These same games also failed with the key dump from the previous
‘Lockpick_RCM’ where others seemed to work fine.

**Comment by waylonflinn** [comment]
Not sure if this is helpful but here’s a detailed changelog:
https://switchbrew.org/wiki/15.0.0

It mentions things like 
“omm: FS permissions now has bitmask 0x0000000000100000 set.”

**Comment by J-D-K** [comment]
Hey, sorry. Things are still pretty hectic for me. I'm hoping things calm down soon so I can take a look and get some things done. I didn't have a chance this past weekend.

**Comment by waylonflinn** [comment]
Thanks for the response man. Let me know how I can help.

**Comment by J-D-K** [comment]
Sorry I dropped off the face of the earth again. Work has been crazy. I'm only here now because I caught covid. I'll dust off my laptop and update libnx later today or tomorrow and get you a new build to see if it helps at all.

**Comment by waylonflinn** [comment]
No problem man. I'll keep an eye out for a new build to test.
Hope you're feeling better soon.

**Comment by J-D-K** [comment]
I double checked to be 100% sure. This is the master branch built with the latest libnx release version. If it doesn't solve the problem, there is something else wrong I'll need to take a look at.
[JKSV.zip](https://github.com/J-D-K/JKSV/files/10023226/JKSV.zip)

**Comment by waylonflinn** [comment]
Awesome, thanks! I’ll check it out.

**Comment by luisdavidsj** [comment]
Hey man I hope you get better soon, In my case, I've tried with the new version 15.0.1, JKSV opens correctly from homebrew menu, but the save files don't seem to restore right, I select an installed and previously opened game from my JKSV save states list, select the last update in example named as: AUTO - myUserName - 2022.05.20 @ 23.18.06 and whtn i check the game it does not restore, all data is empty, BUT when I select another file from my save states, let's say, one old save file, in example, named as: myUserName - 2021.10.02 @18.32.37 it restores correctly! and now I can see all the data in-game, this obviously carries a few problems, new save states are not working or restoring well, but old save states seems to restore just fine, but the problem is that this bring me back-in-time, as the working saves are very old (from 1 year ago) that all my progress from the last year is probably lost.
Well, that's my status bro, i hope this helps. I'll check your repo for the latest news and let me know if you need help.

**Comment by J-D-K** [comment]
It should actually prevent you from trying to import an empty folder or zip. It doesn't have a little pop-up that says `Save data is empty!` or something like that?

**Comment by luisdavidsj** [comment]
The save state appears but restore is not working, no messages or pop-ups show up.
