### ISSUE TITLE
No dkp-pacman (can't build in windows)

### ISSUE THREAD

**Issue by MonfGeiger** [J-D-K/JKSV#164]
I tried my hand at building this from source using the tools shown on the front page building section (used graphical installer for devkitpro for windows 64 bit), made sure to select the switch options and the 3ds options just in-case, restarted, downloaded the source files from the front page in zip, extracted, opened command prompt in admin mode, cd to that extracted directory, and tried the build command from the front page. immediately i got `'dkp-pacman' is not recognized as an internal or external command, operable program or batch file` as a response

I don't know if its because the directory location of my desktop folder is on my secondary (D:) drive (2 TB SSD) and there's some path conflict, that the devkit files are/were on the D: drive as well, or whatever, but im really only doing this so i can try and use the SVI export feature so i can see how it works since i do not see it in the 09/01/2021 build of JKSV (either it isnt implemented in it yet or it is but im too blind to see what option it is right now). if you can tell me that the SVI export feature is in this version of JKSV, then ill consider this solved and feel free to close it. if it isnt, i would appreciate any help towards figuring out why i can't build from source (unless the below instructions are more for linux users than windows users?)

any help at this point would be greatly appreciated, and would hopefully reduce my stress levels from me trying to help my father take care of tax related issues that he just won't stop **BOTHERING ME WITH!!!!** Sorry, not relevant to the matter at hand, but this tax thing is getting to me right now, apologies

**Comment by fennectech** [comment]
DKP-Pacman is someting that must be installed on a linux system (or linux emulation layer)   Your going to need to set up a build environment before you can compile anything. Sent from my iPadOn Nov 9, 2022, at 10:33 AM, MonfGeiger ***@***.***> wrote:﻿
I tried my hand at building this from source using the tools shown on the front page building section (used graphical installer for devkitpro for windows 64 bit), made sure to select the switch options and the 3ds options just in-case, restarted, downloaded the source files from the front page in zip, extracted, opened command prompt in admin mode, cd to that extracted directory, and tried the build command from the front page. immediately i got 'dkp-pacman' is not recognized as an internal or external command, operable program or batch file as a response
I don't know if its because the directory location of my desktop folder is on my secondary (D:) drive (2 TB SSD) and there's some path conflict, that the devkit files are/were on the D: drive as well, or whatever, but im really only doing this so i can try and use the SVI export feature so i can see how it works since i do not see it in the 09/01/2021 build of JKSV (either it isnt implemented in it yet or it is but im too blind to see what option it is right now). if you can tell me that the SVI export feature is in this version of JKSV, then ill consider this solved and feel free to close it. if it isnt, i would appreciate any help towards figuring out why i can't build from source (unless the below instructions are more for linux users than windows users?)
any help at this point would be greatly appreciated, and would hopefully reduce my stress levels from me trying to help my father take care of tax related issues that he just won't stop BOTHERING ME WITH!!!! Sorry, not relevant to the matter at hand, but this tax thing is getting to me right now, apologies

**Comment by fennectech** [comment]
You need to set up a build environment using a linux emulation layer.     DKP-Pacman is a linux package manager.  
https://switchbrew.org/wiki/Setting_up_Development_Environment

**Comment by MonfGeiger** [comment]
well, my fivehead forgot the use MSYS part of the steps and thought it was a command line thing.....i'd close this now, but im reinstalling devkitpro and ill redo the steps all over again. if (and when) i succeed, ill consider this issue closed.

**Comment by MonfGeiger** [comment]
and immediately im running into an issue, says i don't have dkp-pacman even though im sure it downloaded with devkitpro when i ran it, so im trying to install it using the instructions on its github page via wget and then sudo, but it says i dont have sudo, and trying to run ./install-devkitpro-pacman says i need root privileges

god forbid, am i missing ANYTHING else beyond what the below building steps say i need? im damn well sure it grabbed both devkitpro & libnx during install

**Comment by MonfGeiger** [comment]
alright, i just realized the instructions provided are for those compiling it on linux, but since im using the graphical installer windows version of devkitpro, im going to guess the command lines `dkp-pacman -S switch-curl switch-freetype switch-libjpeg-turbo switch-libjson-c switch-libpng switch-libwebp switch-sdl2 switch-sdl2_gfx switch-sdl2_image switch-zlib` will not work out for me with msys in windows, so any help in that regard would be appreciated

**Comment by MonfGeiger** [comment]
says `bash: dkp-pacman not found`

**Comment by MonfGeiger** [comment]
wait, might've gotten it, the dkp part is something linux only, i've been seeing pacman.exe when i was installing devkit pro, ill leave out the dkp part and try it again now

**Comment by fennectech** [comment]
You need to install dkp-pacman first    Following the linux setup directions https://github.com/devkitPro/pacman/releases/tag/v1.0.2

**Comment by MonfGeiger** [comment]
I built it from source, all i had to do was follow the instructions but use `pacman -S switch-curl switch-freetype switch-libjpeg-turbo switch-libjson-c switch-libpng switch-libwebp switch-sdl2 switch-sdl2_gfx switch-sdl2_image switch-zlib` instead, got all the stuff, ran make from source, tested the built nro, and it ran just fine.

oh this feels so good right now. if **anything** is taken from this, i only ask that the build instructions be amended to include something like "if you're running devkitpro from windows, use `pacman -S switch-curl switch-freetype switch-libjpeg-turbo switch-libjson-c switch-libpng switch-libwebp switch-sdl2 switch-sdl2_gfx switch-sdl2_image switch-zlib`, cd to the JKSV-master folder, run make" or something more neat and verbosed along the lines

thank you for tolerating my 7head moment here, peace

**Comment by fennectech** [comment]
Glad to hear you got it working
