### ISSUE TITLE
Google Drive Sync

### ISSUE THREAD

**Issue by k-s-s** [J-D-K/JKSV#210]
I can upload my save to Google drive
But when I zip my save from my PC and upload to the same folder, it doesn't appear on my switch.
Are there any requirements for this?

Thanks

**Comment by J-D-K** [comment]
In order to keep everything smooth, your drive is only synced once upon booting JKSV. Originally drive data was downloaded and fetched upon opening the backup menu, but it added a lot of pauses and stuttering I did not like at all. A lot of people agreed with me too that it would get annoying after a while.

**Comment by k-s-s** [comment]
That works great thanks, sync on boot is more than enough
Thanks
