### ISSUE TITLE
Infinite Logo Loading Screen

### ISSUE THREAD

**Issue by KrushYuppy** [J-D-K/JKSV#223]
When launching JKSV I see the logo and nothing else happens. Nothing shows up in the log file. It doesn't crash or boot out, it just does nothing.

Launching applet mode or full doesn't make any difference. Downgrading causes AMS to crash.

I updated the NRO
I deleted the config file
I deleted the JKSV folder completely 
I'm on the latest version of AMS

I can't use checkpoint since I'm trying to reload ACNH saves. I have not seen anyone else with this exact issue so I'm pretty much out of ideas.

**Comment by impeeza** [comment]
Are you using applet mode or full Hombrew Loader.?

**Comment by J-D-K** [comment]
Do you have a lot of games installed?

**Comment by KrushYuppy** [comment]
Applet mode is when you hold down LR when launching a game right? I'm not sure what full homebrew loader is.

And yes I do have alot of games installed. I can unistall a bunch and see if that fixes it.

**Comment by impeeza** [comment]
Applet mode is when you launch Hombrew Loader using the Image Applet.

Full is when you launch Homebrew Loader pressing R while you launch a game.

**Comment by KrushYuppy** [comment]
Oh yeah I see, not very good on the terminology. 

But yes, I launch full each time. 

I also deleted some games and still samething.

**Comment by J-D-K** [comment]
I was contacted once before by someone having the same issue, but in their case it was because they had hundreds of games installed. They wound up leaving their Switch sit for around 10 minutes after I asked them too, and JKSV eventually started, it just took a while. This might have been pre-SDL though.

I remember considering adding some kind of status or update to the loading screen after that, but because textures need to be loaded on the main thread, I couldn't really figure out a way to do that wouldn't have been a mess at the time.

**Comment by KrushYuppy** [comment]
I think I have less then a hundred games and leaving it on for more than 10 mins it still won't open.

Not sure if this helps; but when I delete the config folder and the JKSV save folder, it will recreate the folders with nothing inside. The log will be completely empty, it creates a trash folder, creates the config folder but again nothing inside.  

Could a folder inside atmosphere contents be screwing with JKSV? I have been using JSKV for a very long time with no problem (I prefer it over checkpoint). I think I started having issues after I updated my switch, not sure though.

**Comment by J-D-K** [comment]
The base folders are created on boot, config is saved at exit, so that is working how it should. JKSV doesn't touch anything outside of its own folders (config and the main JKSV folder), so I doubt it's anything to do with atmosphere. I actually removed the logging early on because it slowed everything down too much, even if it would be useful. I can try logging the boot code in a little while, but it's been a while since I've touched the old code base. I might need some time to figure it out again. It's a mess and I'm not proud of it.

**Comment by KrushYuppy** [comment]
No worries, I might just have to factory reset my console. I need to anyway since I just got a 1TB SD card and need to switch over.

**Comment by KrushYuppy** [comment]
Managed to fix it.

I started deleting random saved game data from the system and it was able to launch now. Not sure what save was an issue or what the problem was but it actually launches now. 

When I get home I'm going to transfer my JKSV saves back to my switch and see if it will still work.

**Comment by J-D-K** [comment]
Glad it worked out in the end, but if it happens again, let me know.
