### ISSUE TITLE
Feature request. PKSM bridge

### ISSUE THREAD

**Issue by fennectech** [J-D-K/JKSV#76]
Would you be willing to add support for the PKSM bridge?  https://github.com/FlagBrew/Checkpoint/blob/v3.6.0/switch/source/pksmbridge.cpp  It allows communication with the 3ds versions of PKSM for save editing on pokemon games

**Comment by fennectech** [comment]
Bolth projects are GPLv3 so licenseing isnt an issue

**Comment by fennectech** [comment]
Any chances on this being a thing?

**Comment by fennectech** [comment]
https://github.com/FlagBrew/Checkpoint/blob/master/switch/source/pksmbridge.cpp  
They have updated the PKSM bridge and it is now in the version available to the public.    It would be really cool to have this functionality in JKSV.  This is currently the only thing checkpoint has that jksv doesn't.  And literally the only reason I personally would have to keep checkpoint on my switch

**Comment by J-D-K** [comment]
Right now dude, cloud backup is taking priority along with fixes and touchups. I did rush a few things towards the end of the UI update because I knew work was going to start picking up and I wouldn't have a ton of time (I'm not happy with some of the menu code at all, specifically drawing and a few other things). Cloud support has been begged for since JKSM existed, believe me. It's one of the most requested things I've gotten in the past 5 years.

I'm not ignoring you, I promise.
